# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queueens', '0002_auto_20171025_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='codigo',
            field=models.CharField(default='None Code', max_length=50),
        ),
    ]
